In [1]:
import csv

In [6]:
training_data_file = r"C:\Users\dasarred\Downloads\data\training_data_example.csv"
validation_data_file = r"C:\Users\dasarred\Downloads\data\validation_data_example.csv"
employee_file = r"C:\Users\dasarred\Downloads\data\employee.csv"

def parse_csv_data(input_file):
    data_list = [] # list of lists
    header_list = [] # list containing just the header row
    with open(input_file, "r") as csv_file:
        parsed_data = csv.reader(csv_file, delimiter=",")
        i = 0
        for row in parsed_data:
            if i == 0:
                header_list = row
            else:
                data_list.append(row)
            i = i + 1

    return data_list, header_list

parse_csv_data(employee_file)

([['1', 'Steve Jobs', '235 Carlaw Ave, Toronto, ON, Canada', 'CEO'],
  ['2', 'Jonathan Ive', '1 Yonge St, Toronto, ON, Canada', 'Engineer'],
  ['3', 'Tim Cook', '1 Infinite Loop, Toronto, ON, Canada', 'IT and Admin'],
  ['4',
   'Larry Page',
   '1600 Amphitheatre Parkway, Hamilton, ON, Canada',
   'Sales'],
  ['5', 'Jonathan Ive', '1 Yonge St, Toronto, ON, Canada', 'Engineer'],
  ['6', 'Eric Schmidt', '250 Carlaw Ave, Toronto, ON, Canada', 'Sales'],
  ['7', 'Don Draper', '783 Park Ave, New York, NY 10021', 'Sales']],
 ['employee id', 'employee name', 'employee address', 'role'])

In [7]:
parse_csv_data(validation_data_file)

([['11/10/2016', 'Travel', '7', 'Taxi ride', '30.00', 'NY Sales tax', '2.66'],
  ['11/12/2016',
   'Meals and Entertainment',
   '1',
   'Dinner with Family',
   '235.00',
   'CA Sales tax',
   '30.55'],
  ['9/2/2016',
   'Computer - Hardware',
   '4',
   'Macbook Air Computer',
   '4000.00',
   'CA Sales tax',
   '520'],
  ['9/2/2016',
   'Office Supplies',
   '4',
   'Paper',
   '20.00',
   'CA Sales tax',
   '2.6'],
  ['9/2/2016', 'Office Supplies', '4', 'Pens', '20.00', 'CA Sales tax', '2.6'],
  ['11/21/2016',
   'Travel',
   '1',
   'Airplane ticket to Miami',
   '200.00',
   'CA Sales tax',
   '26'],
  ['12/4/2016',
   'Meals and Entertainment',
   '2',
   'Starbucks coffee',
   '12.00',
   'CA Sales tax',
   '1.56'],
  ['1/18/2010',
   'Meals and Entertainment',
   '6',
   'Dinner',
   '30.00 ',
   'CA Sales tax',
   '3.9'],
  ['10/5/2016',
   'Meals and Entertainment',
   '4',
   'Dinner with client',
   '220.00',
   'CA Sales tax',
   '28.6'],
  ['12/2/2016',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '180.00',
   'CA Sales tax',
   '23.4'],
  ['2/14/2017',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '500.00',
   'CA Sales tax',
   '65'],
  ['2/14/2016',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '600.00',
   'CA Sales tax',
   '78']],
 ['date',
  'category',
  'employee id',
  'expense description',
  'pre-tax amount',
  'tax name',
  'tax amount'])

In [8]:
parse_csv_data(training_data_file)

([['11/1/2016', 'Travel', '7', 'Taxi ride', '40.00', 'NY Sales tax', '3.55'],
  ['11/15/2016',
   'Meals and Entertainment',
   '1',
   'Team lunch',
   '235.00',
   'CA Sales tax',
   '30.55'],
  ['11/30/2016',
   'Computer - Hardware',
   '3',
   'HP Laptop Computer',
   '999.00',
   'CA Sales tax',
   '129.87'],
  ['11/14/2016',
   'Computer - Software',
   '3',
   'Microsoft Office',
   '899.00',
   'CA Sales tax',
   '116.87'],
  ['11/6/2016',
   'Computer - Software',
   '4',
   'Dropbox Subscription',
   '50.00',
   'CA Sales tax',
   '6.5'],
  ['11/3/2016',
   'Computer - Software',
   '3',
   'Dropbox Subscription',
   '50.00',
   'CA Sales tax',
   '6.5'],
  ['12/9/2016',
   'Meals and Entertainment',
   '6',
   'Coffee with Steve',
   '300.00',
   'CA Sales tax',
   '39'],
  ['11/12/2016', 'Travel', '4', 'Taxi ride', '230.00', 'CA Sales tax', '29.9'],
  ['11/21/2016',
   'Meals and Entertainment',
   '7',
   'Client dinner',
   '200.00',
   'NY Sales tax',
   '17.75'],
  ['10/4/2016',
   'Travel',
   '6',
   'Flight to Miami',
   '200.00',
   'CA Sales tax',
   '26'],
  ['10/12/2016',
   'Computer - Hardware',
   '7',
   'Macbook Air Computer',
   '1999.00 ',
   'NY Sales tax',
   '177.41'],
  ['12/11/2016',
   'Computer - Software',
   '1',
   'iCloud Subscription',
   '15.00',
   'CA Sales tax',
   '1.95'],
  ['9/18/2016', 'Travel', '1', 'Taxi ride', '60.00', 'CA Sales tax', '7.8'],
  ['9/30/2016',
   'Office Supplies',
   '3',
   'Paper',
   '200.00',
   'CA Sales tax',
   '26'],
  ['12/30/2016',
   'Meals and Entertainment',
   '4',
   'Dinner with potential client',
   '200.00',
   'CA Sales tax',
   '26'],
  ['11/6/2016',
   'Computer - Hardware',
   '6',
   'iPhone',
   '200.00',
   'CA Sales tax',
   '26'],
  ['11/7/2016',
   'Travel',
   '1',
   'Airplane ticket to NY',
   '200.00',
   'CA Sales tax',
   '26'],
  ['12/3/2016',
   'Meals and Entertainment',
   '5',
   'Starbucks coffee',
   '4.00',
   'CA Sales tax',
   '0.52'],
  ['12/18/2016',
   'Travel',
   '6',
   'Airplane ticket to NY',
   '1500.00 ',
   'CA Sales tax',
   '195'],
  ['12/15/2016',
   'Meals and Entertainment',
   '4',
   'Dinner with client',
   '200.00',
   'CA Sales tax',
   '26'],
  ['12/1/2016',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '210.00',
   'CA Sales tax',
   '27.3'],
  ['12/8/2016',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '180.00',
   'CA Sales tax',
   '23.4'],
  ['12/31/2016',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '1000.00',
   'CA Sales tax',
   '130'],
  ['12/9/2016',
   'Meals and Entertainment',
   '4',
   'Dinner',
   '30.00',
   'CA Sales tax',
   '3.9']],
 ['date',
  'category',
  'employee id',
  'expense description',
  'pre-tax amount',
  'tax name',
  'tax amount'])